// Endpoint metadata is derived from Pylon's public OpenAPI document.
// Source: https://static.usepylon.com/openapi.json

export type FieldKind = "array" | "boolean" | "integer" | "number" | "object" | "string";
export type FieldDefinition = readonly [name: string, kind: FieldKind, required: boolean];

export type EndpointDefinition = {
  readonly bodyContentType?: "application/json" | "multipart/form-data";
  readonly bodyFields?: readonly FieldDefinition[];
  readonly method: "DELETE" | "GET" | "PATCH" | "POST" | "PUT";
  readonly mutates: boolean;
  readonly name: string;
  readonly path: string;
  readonly queryFields?: readonly FieldDefinition[];
  readonly resource: string;
  readonly summary: string;
};

export const ENDPOINT_DEFINITIONS = [
  {
    name: "createAccount",
    resource: "accounts",
    method: "POST",
    path: "/accounts",
    summary: "Create a new account",
    bodyContentType: "application/json",
    bodyFields: [
      ["account_type", "string", false],
      ["channels", "array", false],
      ["custom_fields", "array", false],
      ["domain", "string", false],
      ["domains", "array", false],
      ["external_ids", "array", false],
      ["logo_url", "string", false],
      ["name", "string", true],
      ["owner_id", "string", false],
      ["primary_domain", "string", false],
      ["subaccount_ids", "array", false],
      ["tags", "array", false],
    ],
    mutates: true,
  },
  {
    name: "updateAccounts",
    resource: "accounts",
    method: "PATCH",
    path: "/accounts",
    summary: "Update multiple accounts",
    bodyContentType: "application/json",
    bodyFields: [
      ["account_ids", "array", true],
      ["account_type", "string", false],
      ["custom_fields", "array", false],
      ["owner_id", "string", false],
      ["tags", "array", false],
      ["tags_apply_mode", "string", false],
    ],
    mutates: true,
  },
  {
    name: "createAccountHighlight",
    resource: "account-highlights",
    method: "POST",
    path: "/accounts/{account_id}/highlights",
    summary: "Create an account highlight",
    bodyContentType: "application/json",
    bodyFields: [
      ["content_html", "string", true],
      ["expires_at", "string", false],
    ],
    mutates: true,
  },
  {
    name: "updateAccountHighlight",
    resource: "account-highlights",
    method: "PATCH",
    path: "/accounts/{account_id}/highlights/{highlight_id}",
    summary: "Update an account highlight",
    bodyContentType: "application/json",
    bodyFields: [
      ["content_html", "string", false],
      ["expires_at", "string", false],
    ],
    mutates: true,
  },
  {
    name: "deleteAccountHighlight",
    resource: "account-highlights",
    method: "DELETE",
    path: "/accounts/{account_id}/highlights/{highlight_id}",
    summary: "Delete an account highlight",
    mutates: true,
  },
  {
    name: "updateAccount",
    resource: "accounts",
    method: "PATCH",
    path: "/accounts/{id}",
    summary: "Update an existing account",
    bodyContentType: "application/json",
    bodyFields: [
      ["account_type", "string", false],
      ["channels", "array", false],
      ["custom_fields", "array", false],
      ["domains", "array", false],
      ["external_ids", "array", false],
      ["is_disabled", "boolean", false],
      ["logo_url", "string", false],
      ["name", "string", false],
      ["owner_id", "string", false],
      ["primary_domain", "string", false],
      ["subaccount_ids", "array", false],
      ["tags", "array", false],
    ],
    mutates: true,
  },
  {
    name: "deleteAccount",
    resource: "accounts",
    method: "DELETE",
    path: "/accounts/{id}",
    summary: "Delete an existing account",
    mutates: true,
  },
  {
    name: "createAccountActivity",
    resource: "accounts",
    method: "POST",
    path: "/accounts/{id}/activities",
    summary: "Create a new activity for an account",
    bodyContentType: "application/json",
    bodyFields: [
      ["body_html", "string", false],
      ["contact_id", "string", false],
      ["happened_at", "string", false],
      ["link", "string", false],
      ["link_text", "string", false],
      ["slug", "string", true],
      ["user_id", "string", false],
    ],
    mutates: true,
  },
  {
    name: "uploadAccountFile",
    resource: "accounts",
    method: "POST",
    path: "/accounts/{id}/files",
    summary: "Upload files to an account",
    bodyContentType: "multipart/form-data",
    bodyFields: [
      ["file", "string", false],
      ["file_url", "string", false],
    ],
    mutates: true,
  },
  {
    name: "listActivityTypes",
    resource: "activity-types",
    method: "GET",
    path: "/activity-types",
    summary: "Get custom activity types",
    mutates: false,
  },
  {
    name: "createAttachment",
    resource: "attachments",
    method: "POST",
    path: "/attachments",
    summary: "Create an attachment",
    bodyContentType: "multipart/form-data",
    bodyFields: [
      ["description", "string", false],
      ["file", "string", false],
      ["file_url", "string", false],
    ],
    mutates: true,
  },
  {
    name: "listAuditLogs",
    resource: "audit_logs",
    method: "GET",
    path: "/audit-logs",
    summary: "Get a list of audit logs",
    queryFields: [
      ["cursor", "string", false],
      ["limit", "integer", false],
    ],
    mutates: false,
  },
  {
    name: "searchAuditLogs",
    resource: "audit_logs",
    method: "POST",
    path: "/audit-logs/search",
    summary: "Search audit logs with filters",
    bodyContentType: "application/json",
    bodyFields: [
      ["cursor", "string", false],
      ["filter", "object", false],
      ["limit", "integer", false],
    ],
    mutates: false,
  },
  {
    name: "getCallRecording",
    resource: "call-recordings",
    method: "GET",
    path: "/call-recordings/{id}",
    summary: "Get a call recording by its ID",
    mutates: false,
  },
  {
    name: "updateCallRecording",
    resource: "call-recordings",
    method: "PATCH",
    path: "/call-recordings/{id}",
    summary: "Update a call recording",
    bodyContentType: "application/json",
    bodyFields: [
      ["account_id", "string", false],
      ["custom_fields", "array", false],
    ],
    mutates: true,
  },
  {
    name: "searchCallRecordings",
    resource: "call-recordings",
    method: "POST",
    path: "/call-recordings/search",
    summary: "Search for call recordings by a given filter",
    bodyContentType: "application/json",
    bodyFields: [
      ["cursor", "string", false],
      ["filter", "object", false],
      ["limit", "integer", false],
    ],
    mutates: false,
  },
  {
    name: "createContact",
    resource: "contacts",
    method: "POST",
    path: "/contacts",
    summary: "Create a new contact",
    bodyContentType: "application/json",
    bodyFields: [
      ["account_external_id", "string", false],
      ["account_id", "string", false],
      ["avatar_url", "string", false],
      ["custom_fields", "array", false],
      ["email", "string", false],
      ["external_ids", "array", false],
      ["name", "string", true],
      ["phone_numbers", "array", false],
      ["portal_role", "string", false],
      ["portal_role_id", "string", false],
      ["primary_phone_number", "string", false],
    ],
    mutates: true,
  },
  {
    name: "updateContact",
    resource: "contacts",
    method: "PATCH",
    path: "/contacts/{id}",
    summary: "Update an existing contact",
    bodyContentType: "application/json",
    bodyFields: [
      ["account_external_id", "string", false],
      ["account_id", "string", false],
      ["avatar_url", "string", false],
      ["custom_fields", "array", false],
      ["email", "string", false],
      ["emails", "array", false],
      ["external_ids", "array", false],
      ["name", "string", false],
      ["phone_numbers", "array", false],
      ["portal_role", "string", false],
      ["portal_role_id", "string", false],
      ["primary_phone_number", "string", false],
    ],
    mutates: true,
  },
  {
    name: "deleteContact",
    resource: "contacts",
    method: "DELETE",
    path: "/contacts/{id}",
    summary: "Delete an existing contact",
    mutates: true,
  },
  {
    name: "listCustomFields",
    resource: "custom-fields",
    method: "GET",
    path: "/custom-fields",
    summary: "Get all custom fields",
    queryFields: [["object_type", "string", true]],
    mutates: false,
  },
  {
    name: "createCustomField",
    resource: "custom-fields",
    method: "POST",
    path: "/custom-fields",
    summary: "Create a custom field",
    bodyContentType: "application/json",
    bodyFields: [
      ["default_value", "string", false],
      ["default_values", "array", false],
      ["description", "string", false],
      ["label", "string", true],
      ["object_type", "string", true],
      ["select_options", "array", false],
      ["slug", "string", false],
      ["type", "string", true],
    ],
    mutates: true,
  },
  {
    name: "getCustomField",
    resource: "custom-fields",
    method: "GET",
    path: "/custom-fields/{id}",
    summary: "Get a custom field by its ID",
    mutates: false,
  },
  {
    name: "updateCustomField",
    resource: "custom-fields",
    method: "PATCH",
    path: "/custom-fields/{id}",
    summary: "Update a custom field",
    bodyContentType: "application/json",
    bodyFields: [
      ["default_value", "string", false],
      ["default_values", "array", false],
      ["description", "string", false],
      ["label", "string", false],
      ["select_options", "array", false],
      ["slug", "string", false],
    ],
    mutates: true,
  },
  {
    name: "listCustomObjects",
    resource: "custom-objects",
    method: "GET",
    path: "/custom-objects/{type}",
    summary: "List custom objects",
    queryFields: [
      ["cursor", "string", false],
      ["limit", "integer", false],
    ],
    mutates: false,
  },
  {
    name: "createCustomObject",
    resource: "custom-objects",
    method: "POST",
    path: "/custom-objects/{type}",
    summary: "Create a custom object",
    bodyContentType: "application/json",
    bodyFields: [
      ["custom_fields", "object", false],
      ["name", "string", true],
    ],
    mutates: true,
  },
  {
    name: "updateCustomObjects",
    resource: "custom-objects",
    method: "PATCH",
    path: "/custom-objects/{type}",
    summary: "Bulk update custom objects",
    bodyContentType: "application/json",
    bodyFields: [
      ["custom_fields", "object", false],
      ["ids", "array", true],
    ],
    mutates: true,
  },
  {
    name: "getCustomObject",
    resource: "custom-objects",
    method: "GET",
    path: "/custom-objects/{type}/{id}",
    summary: "Get a custom object",
    mutates: false,
  },
  {
    name: "updateCustomObject",
    resource: "custom-objects",
    method: "PATCH",
    path: "/custom-objects/{type}/{id}",
    summary: "Update a custom object",
    bodyContentType: "application/json",
    bodyFields: [
      ["custom_fields", "object", false],
      ["name", "string", false],
    ],
    mutates: true,
  },
  {
    name: "deleteCustomObject",
    resource: "custom-objects",
    method: "DELETE",
    path: "/custom-objects/{type}/{id}",
    summary: "Delete a custom object",
    mutates: true,
  },
  {
    name: "searchCustomObjects",
    resource: "custom-objects",
    method: "POST",
    path: "/custom-objects/{type}/search",
    summary: "Search for custom objects by a given filter",
    bodyContentType: "application/json",
    bodyFields: [
      ["cursor", "string", false],
      ["filter", "object", true],
      ["limit", "integer", false],
    ],
    mutates: false,
  },
  {
    name: "getFeatureRequest",
    resource: "feature-requests",
    method: "GET",
    path: "/feature-requests/{id}",
    summary: "Get a feature request by ID",
    queryFields: [["fetch_evidence", "boolean", false]],
    mutates: false,
  },
  {
    name: "updateFeatureRequest",
    resource: "feature-requests",
    method: "PATCH",
    path: "/feature-requests/{id}",
    summary: "Update a feature request",
    bodyContentType: "application/json",
    bodyFields: [
      ["custom_fields", "array", false],
      ["request_status", "string", false],
    ],
    mutates: true,
  },
  {
    name: "deleteFeatureRequest",
    resource: "feature-requests",
    method: "DELETE",
    path: "/feature-requests/{id}",
    summary: "Delete a feature request",
    mutates: true,
  },
  {
    name: "searchFeatureRequests",
    resource: "feature-requests",
    method: "POST",
    path: "/feature-requests/search",
    summary: "Search or list feature requests",
    bodyContentType: "application/json",
    bodyFields: [
      ["account_ids", "array", false],
      ["limit", "integer", false],
      ["query", "string", false],
      ["request_statuses", "array", false],
    ],
    mutates: false,
  },
  {
    name: "importContact",
    resource: "import",
    method: "POST",
    path: "/import/contacts",
    summary: "Import a new contact",
    bodyContentType: "application/json",
    bodyFields: [
      ["account_id", "string", false],
      ["avatar_url", "string", false],
      ["custom_fields", "array", false],
      ["email", "string", true],
      ["name", "string", true],
      ["portal_role", "string", false],
    ],
    mutates: true,
  },
  {
    name: "importIssue",
    resource: "import",
    method: "POST",
    path: "/import/issues",
    summary: "Import an issue",
    bodyContentType: "application/json",
    bodyFields: [
      ["account_id", "string", false],
      ["assignee_id", "string", false],
      ["attachment_urls", "array", false],
      ["created_at", "string", false],
      ["custom_fields", "array", false],
      ["external_issues", "array", false],
      ["external_refs", "object", false],
      ["first_response_time", "string", false],
      ["messages", "array", true],
      ["requester_id", "string", false],
      ["resolution_time", "string", false],
      ["state", "string", true],
      ["tags", "array", false],
      ["team_id", "string", false],
      ["title", "string", true],
      ["updated_at", "string", false],
    ],
    mutates: true,
  },
  {
    name: "importIssueMessages",
    resource: "import",
    method: "POST",
    path: "/import/issues/{id}/messages",
    summary: "Import messages onto an existing issue",
    bodyContentType: "application/json",
    bodyFields: [["messages", "array", true]],
    mutates: true,
  },
  {
    name: "listIssueStatuses",
    resource: "issue-statuses",
    method: "GET",
    path: "/issue-statuses",
    summary: "Get all issue statuses",
    mutates: false,
  },
  {
    name: "createIssue",
    resource: "issues",
    method: "POST",
    path: "/issues",
    summary: "Create a new issue",
    bodyContentType: "application/json",
    bodyFields: [
      ["account_id", "string", false],
      ["assignee_id", "string", false],
      ["attachment_urls", "array", false],
      ["author_unverified", "boolean", false],
      ["body_html", "string", true],
      ["contact_id", "string", false],
      ["created_at", "string", false],
      ["custom_fields", "array", false],
      ["destination_metadata", "object", false],
      ["priority", "string", false],
      ["requester_avatar_url", "string", false],
      ["requester_email", "string", false],
      ["requester_id", "string", false],
      ["requester_name", "string", false],
      ["tags", "array", false],
      ["team_id", "string", false],
      ["title", "string", true],
      ["user_id", "string", false],
    ],
    mutates: true,
  },
  {
    name: "updateIssue",
    resource: "issues",
    method: "PATCH",
    path: "/issues/{id}",
    summary: "Update an existing issue",
    bodyContentType: "application/json",
    bodyFields: [
      ["account_id", "string", false],
      ["assignee_id", "string", false],
      ["custom_fields", "array", false],
      ["customer_portal_visible", "boolean", false],
      ["requester_id", "string", false],
      ["requestor_id", "string", false],
      ["state", "string", false],
      ["tags", "array", false],
      ["team_id", "string", false],
      ["title", "string", false],
      ["type", "string", false],
    ],
    mutates: true,
  },
  {
    name: "deleteIssue",
    resource: "issues",
    method: "DELETE",
    path: "/issues/{id}",
    summary: "Delete an existing issue",
    mutates: true,
  },
  {
    name: "createIssueAiResponse",
    resource: "issues",
    method: "POST",
    path: "/issues/{id}/ai-response",
    summary: "Create an AI response for an issue",
    bodyContentType: "application/json",
    bodyFields: [
      ["ai_agent_id", "string", true],
      ["post_as_internal_note", "boolean", false],
    ],
    mutates: true,
  },
  {
    name: "linkExternalIssue",
    resource: "issues",
    method: "POST",
    path: "/issues/{id}/external-issues",
    summary: "Link or unlink external issues to/from an issue",
    bodyContentType: "application/json",
    bodyFields: [
      ["external_issue_id", "string", true],
      ["operation", "string", false],
      ["source", "string", true],
    ],
    mutates: true,
  },
  {
    name: "updateIssueFollowers",
    resource: "issues",
    method: "POST",
    path: "/issues/{id}/followers",
    summary: "Add or remove followers to/from an issue",
    bodyContentType: "application/json",
    bodyFields: [
      ["contact_ids", "array", false],
      ["operation", "string", false],
      ["user_ids", "array", false],
    ],
    mutates: true,
  },
  {
    name: "listIssueMessages",
    resource: "messages",
    method: "GET",
    path: "/issues/{id}/messages",
    summary: "Get all messages on an issue",
    mutates: false,
  },
  {
    name: "deleteIssueMessage",
    resource: "messages",
    method: "DELETE",
    path: "/issues/{id}/messages/{message_id}",
    summary: "Delete a message",
    mutates: true,
  },
  {
    name: "redactIssueMessage",
    resource: "messages",
    method: "POST",
    path: "/issues/{id}/messages/{message_id}/redact",
    summary: "Redact a message",
    mutates: true,
  },
  {
    name: "createIssueNote",
    resource: "messages",
    method: "POST",
    path: "/issues/{id}/note",
    summary: "Create an internal note on an issue",
    bodyContentType: "application/json",
    bodyFields: [
      ["attachment_urls", "array", false],
      ["body_html", "string", true],
      ["message_id", "string", false],
      ["thread_id", "string", false],
      ["thread_name", "string", false],
      ["user_id", "string", false],
    ],
    mutates: true,
  },
  {
    name: "createIssueReply",
    resource: "messages",
    method: "POST",
    path: "/issues/{id}/reply",
    summary: "Reply to an issue",
    bodyContentType: "application/json",
    bodyFields: [
      ["attachment_urls", "array", false],
      ["body_html", "string", true],
      ["contact_id", "string", false],
      ["custom_source", "object", false],
      ["email_info", "object", false],
      ["message_id", "string", true],
      ["user_id", "string", false],
    ],
    mutates: true,
  },
  {
    name: "snoozeIssue",
    resource: "issues",
    method: "POST",
    path: "/issues/{id}/snooze",
    summary: "Snooze an issue",
    bodyContentType: "application/json",
    bodyFields: [["snooze_until", "string", true]],
    mutates: true,
  },
  {
    name: "listIssueThreads",
    resource: "messages",
    method: "GET",
    path: "/issues/{id}/threads",
    summary: "Get all threads on an issue",
    mutates: false,
  },
  {
    name: "createIssueThread",
    resource: "messages",
    method: "POST",
    path: "/issues/{id}/threads",
    summary: "Create a thread on an issue",
    bodyContentType: "application/json",
    bodyFields: [["name", "string", false]],
    mutates: true,
  },
  {
    name: "listIssueVoiceCalls",
    resource: "voice_calls",
    method: "GET",
    path: "/issues/{id}/voice-calls",
    summary: "Get voice calls (with recordings and transcripts) for an issue.",
    mutates: false,
  },
  {
    name: "listKnowledgeBases",
    resource: "knowledge-bases",
    method: "GET",
    path: "/knowledge-bases",
    summary: "Get all knowledge bases",
    mutates: false,
  },
  {
    name: "getKnowledgeBase",
    resource: "knowledge-bases",
    method: "GET",
    path: "/knowledge-bases/{id}",
    summary: "Get a knowledge base by its ID",
    mutates: false,
  },
  {
    name: "listKnowledgeBaseArticles",
    resource: "articles",
    method: "GET",
    path: "/knowledge-bases/{id}/articles",
    summary: "Get all articles in a knowledge base",
    queryFields: [
      ["cursor", "string", false],
      ["limit", "integer", false],
      ["language", "string", false],
    ],
    mutates: false,
  },
  {
    name: "createKnowledgeBaseArticle",
    resource: "articles",
    method: "POST",
    path: "/knowledge-bases/{id}/articles",
    summary: "Create an article",
    bodyContentType: "application/json",
    bodyFields: [
      ["author_user_id", "string", true],
      ["body_html", "string", true],
      ["collection_id", "string", false],
      ["is_published", "boolean", false],
      ["is_unlisted", "boolean", false],
      ["slug", "string", false],
      ["title", "string", true],
      ["translations", "array", false],
      ["visibility_config", "object", false],
    ],
    mutates: true,
  },
  {
    name: "getKnowledgeBaseArticle",
    resource: "articles",
    method: "GET",
    path: "/knowledge-bases/{id}/articles/{article_id}",
    summary: "Get an article by its ID",
    queryFields: [["language", "string", false]],
    mutates: false,
  },
  {
    name: "updateKnowledgeBaseArticle",
    resource: "articles",
    method: "PATCH",
    path: "/knowledge-bases/{id}/articles/{article_id}",
    summary: "Update an article",
    bodyContentType: "application/json",
    bodyFields: [
      ["body_html", "string", false],
      ["is_unlisted", "boolean", false],
      ["language", "string", false],
      ["publish_updated_body_html", "boolean", false],
      ["title", "string", false],
      ["visibility_config", "object", false],
    ],
    mutates: true,
  },
  {
    name: "deleteKnowledgeBaseArticle",
    resource: "articles",
    method: "DELETE",
    path: "/knowledge-bases/{id}/articles/{article_id}",
    summary: "Delete an article",
    mutates: true,
  },
  {
    name: "requestKnowledgeBaseArticleReview",
    resource: "articles",
    method: "POST",
    path: "/knowledge-bases/{id}/articles/{article_id}/request-review",
    summary: "Request review on an article",
    bodyContentType: "application/json",
    bodyFields: [
      ["request_ai_review", "boolean", false],
      ["reviewer_user_ids", "array", false],
    ],
    mutates: true,
  },
  {
    name: "listKnowledgeBaseCollections",
    resource: "collections",
    method: "GET",
    path: "/knowledge-bases/{id}/collections",
    summary: "Get all collections in a knowledge base",
    mutates: false,
  },
  {
    name: "createKnowledgeBaseCollection",
    resource: "collections",
    method: "POST",
    path: "/knowledge-bases/{id}/collections",
    summary: "Create a collection",
    bodyContentType: "application/json",
    bodyFields: [
      ["description", "string", false],
      ["parent_collection_id", "string", false],
      ["slug", "string", false],
      ["title", "string", true],
    ],
    mutates: true,
  },
  {
    name: "getKnowledgeBaseCollection",
    resource: "collections",
    method: "GET",
    path: "/knowledge-bases/{id}/collections/{collection_id}",
    summary: "Get a collection by its ID",
    mutates: false,
  },
  {
    name: "updateKnowledgeBaseCollection",
    resource: "collections",
    method: "PATCH",
    path: "/knowledge-bases/{id}/collections/{collection_id}",
    summary: "Update a collection",
    bodyContentType: "application/json",
    bodyFields: [
      ["description", "string", false],
      ["slug", "string", false],
      ["title", "string", false],
      ["visibility_config", "object", false],
    ],
    mutates: true,
  },
  {
    name: "deleteKnowledgeBaseCollection",
    resource: "collections",
    method: "DELETE",
    path: "/knowledge-bases/{id}/collections/{collection_id}",
    summary: "Delete a collection",
    mutates: true,
  },
  {
    name: "createKnowledgeBaseRouteRedirect",
    resource: "route-redirects",
    method: "POST",
    path: "/knowledge-bases/{id}/route-redirects",
    summary: "Create a new route redirect",
    bodyContentType: "application/json",
    bodyFields: [
      ["from_path", "string", true],
      ["language", "string", false],
      ["object_id", "string", true],
      ["object_type", "string", true],
    ],
    mutates: true,
  },
  {
    name: "listMacroGroups",
    resource: "macros",
    method: "GET",
    path: "/macro-groups",
    summary: "Get all macro groups",
    mutates: false,
  },
  {
    name: "listMacros",
    resource: "macros",
    method: "GET",
    path: "/macros",
    summary: "Get all macros",
    queryFields: [["macro_group_id", "string", false]],
    mutates: false,
  },
  {
    name: "createMacro",
    resource: "macros",
    method: "POST",
    path: "/macros",
    summary: "Create a new macro",
    bodyContentType: "application/json",
    bodyFields: [
      ["conditions", "object", false],
      ["macro_group_id", "string", true],
      ["name", "string", true],
      ["text_html", "string", true],
      ["text_type", "string", false],
      ["visibility", "object", false],
    ],
    mutates: true,
  },
  {
    name: "getMacro",
    resource: "macros",
    method: "GET",
    path: "/macros/{id}",
    summary: "Get a macro by its ID",
    mutates: false,
  },
  {
    name: "updateMacro",
    resource: "macros",
    method: "PATCH",
    path: "/macros/{id}",
    summary: "Update a macro",
    bodyContentType: "application/json",
    bodyFields: [
      ["conditions", "object", false],
      ["macro_group_id", "string", false],
      ["name", "string", false],
      ["text_html", "string", false],
      ["text_type", "string", false],
      ["visibility", "object", false],
    ],
    mutates: true,
  },
  {
    name: "createMilestone",
    resource: "milestones",
    method: "POST",
    path: "/milestones",
    summary: "Create a milestone",
    bodyContentType: "application/json",
    bodyFields: [
      ["account_id", "string", false],
      ["due_date", "string", false],
      ["name", "string", true],
      ["project_id", "string", true],
    ],
    mutates: true,
  },
  {
    name: "getMilestone",
    resource: "milestones",
    method: "GET",
    path: "/milestones/{id}",
    summary: "Get a milestone by its ID",
    mutates: false,
  },
  {
    name: "updateMilestone",
    resource: "milestones",
    method: "PATCH",
    path: "/milestones/{id}",
    summary: "Update a milestone",
    bodyContentType: "application/json",
    bodyFields: [
      ["due_date", "string", false],
      ["name", "string", false],
    ],
    mutates: true,
  },
  {
    name: "deleteMilestone",
    resource: "milestones",
    method: "DELETE",
    path: "/milestones/{id}",
    summary: "Delete a milestone",
    mutates: true,
  },
  {
    name: "createProject",
    resource: "projects",
    method: "POST",
    path: "/projects",
    summary: "Create a project",
    bodyContentType: "application/json",
    bodyFields: [
      ["account_id", "string", true],
      ["customer_portal_visible", "boolean", false],
      ["description_html", "string", false],
      ["end_date", "string", false],
      ["name", "string", true],
      ["owner_id", "string", false],
      ["project_template_id", "string", false],
      ["start_date", "string", false],
    ],
    mutates: true,
  },
  {
    name: "getProject",
    resource: "projects",
    method: "GET",
    path: "/projects/{id}",
    summary: "Get a project by its ID",
    mutates: false,
  },
  {
    name: "updateProject",
    resource: "projects",
    method: "PATCH",
    path: "/projects/{id}",
    summary: "Update a project",
    bodyContentType: "application/json",
    bodyFields: [
      ["custom_fields", "array", false],
      ["customer_portal_visible", "boolean", false],
      ["description_html", "string", false],
      ["end_date", "string", false],
      ["is_archived", "boolean", false],
      ["name", "string", false],
      ["owner_id", "string", false],
      ["start_date", "string", false],
    ],
    mutates: true,
  },
  {
    name: "deleteProject",
    resource: "projects",
    method: "DELETE",
    path: "/projects/{id}",
    summary: "Delete an existing project",
    mutates: true,
  },
  {
    name: "searchProjects",
    resource: "projects",
    method: "POST",
    path: "/projects/search",
    summary: "Search for projects by a given filter",
    bodyContentType: "application/json",
    bodyFields: [
      ["cursor", "string", false],
      ["filter", "object", false],
      ["limit", "integer", false],
    ],
    mutates: false,
  },
  {
    name: "listSurveys",
    resource: "surveys",
    method: "GET",
    path: "/surveys",
    summary: "Get all surveys",
    mutates: false,
  },
  {
    name: "getSurvey",
    resource: "surveys",
    method: "GET",
    path: "/surveys/{id}",
    summary: "Get a survey by its ID",
    mutates: false,
  },
  {
    name: "listSurveyResponses",
    resource: "surveys",
    method: "GET",
    path: "/surveys/{id}/responses",
    summary: "Get survey responses for a survey",
    queryFields: [
      ["submitted_after", "string", false],
      ["submitted_before", "string", false],
      ["account_id", "string", false],
      ["contact_id", "string", false],
      ["cursor", "string", false],
      ["limit", "integer", false],
    ],
    mutates: false,
  },
  {
    name: "searchSurveys",
    resource: "surveys",
    method: "POST",
    path: "/surveys/search",
    summary: "Search for surveys by a given filter",
    bodyContentType: "application/json",
    bodyFields: [
      ["filter", "object", false],
      ["limit", "integer", false],
    ],
    mutates: false,
  },
  {
    name: "listTags",
    resource: "tags",
    method: "GET",
    path: "/tags",
    summary: "Get all tags",
    mutates: false,
  },
  {
    name: "createTag",
    resource: "tags",
    method: "POST",
    path: "/tags",
    summary: "Create a new tag",
    bodyContentType: "application/json",
    bodyFields: [
      ["hex_color", "string", false],
      ["object_type", "string", true],
      ["value", "string", true],
    ],
    mutates: true,
  },
  {
    name: "getTag",
    resource: "tags",
    method: "GET",
    path: "/tags/{id}",
    summary: "Get a tag by its ID",
    mutates: false,
  },
  {
    name: "updateTag",
    resource: "tags",
    method: "PATCH",
    path: "/tags/{id}",
    summary: "Update an existing tag",
    bodyContentType: "application/json",
    bodyFields: [
      ["hex_color", "string", false],
      ["value", "string", false],
    ],
    mutates: true,
  },
  {
    name: "deleteTag",
    resource: "tags",
    method: "DELETE",
    path: "/tags/{id}",
    summary: "Delete an existing tag",
    mutates: true,
  },
  {
    name: "listTasks",
    resource: "tasks",
    method: "GET",
    path: "/tasks",
    summary: "Get all tasks",
    queryFields: [
      ["cursor", "string", false],
      ["limit", "integer", false],
    ],
    mutates: false,
  },
  {
    name: "createTask",
    resource: "tasks",
    method: "POST",
    path: "/tasks",
    summary: "Create a task",
    bodyContentType: "application/json",
    bodyFields: [
      ["account_id", "string", false],
      ["assignee_id", "string", false],
      ["body_html", "string", false],
      ["custom_fields", "array", false],
      ["customer_portal_visible", "boolean", false],
      ["due_date", "string", false],
      ["milestone_id", "string", false],
      ["project_id", "string", false],
      ["status", "string", false],
      ["title", "string", true],
    ],
    mutates: true,
  },
  {
    name: "getTask",
    resource: "tasks",
    method: "GET",
    path: "/tasks/{id}",
    summary: "Get a task by its ID",
    mutates: false,
  },
  {
    name: "updateTask",
    resource: "tasks",
    method: "PATCH",
    path: "/tasks/{id}",
    summary: "Update a task",
    bodyContentType: "application/json",
    bodyFields: [
      ["assignee_id", "string", false],
      ["body_html", "string", false],
      ["custom_fields", "array", false],
      ["customer_portal_visible", "boolean", false],
      ["due_date", "string", false],
      ["milestone_id", "string", false],
      ["project_id", "string", false],
      ["status", "string", false],
      ["title", "string", false],
    ],
    mutates: true,
  },
  {
    name: "deleteTask",
    resource: "tasks",
    method: "DELETE",
    path: "/tasks/{id}",
    summary: "Delete an existing task",
    mutates: true,
  },
  {
    name: "listTaskComments",
    resource: "tasks",
    method: "GET",
    path: "/tasks/{id}/comments",
    summary: "Get comments for a task",
    mutates: false,
  },
  {
    name: "createTaskComment",
    resource: "tasks",
    method: "POST",
    path: "/tasks/{id}/comments",
    summary: "Create a comment on a task",
    bodyContentType: "application/json",
    bodyFields: [["body_html", "string", true]],
    mutates: true,
  },
  {
    name: "updateTaskComment",
    resource: "tasks",
    method: "PATCH",
    path: "/tasks/{id}/comments/{comment_id}",
    summary: "Update a comment on a task",
    bodyContentType: "application/json",
    bodyFields: [["body_html", "string", true]],
    mutates: true,
  },
  {
    name: "deleteTaskComment",
    resource: "tasks",
    method: "DELETE",
    path: "/tasks/{id}/comments/{comment_id}",
    summary: "Delete a comment on a task",
    mutates: true,
  },
  {
    name: "searchTasks",
    resource: "tasks",
    method: "POST",
    path: "/tasks/search",
    summary: "Search for tasks by a given filter",
    bodyContentType: "application/json",
    bodyFields: [
      ["cursor", "string", false],
      ["filter", "object", false],
      ["limit", "integer", false],
    ],
    mutates: false,
  },
  {
    name: "createTeam",
    resource: "teams",
    method: "POST",
    path: "/teams",
    summary: "Create a new team",
    bodyContentType: "application/json",
    bodyFields: [
      ["name", "string", false],
      ["user_ids", "array", false],
    ],
    mutates: true,
  },
  {
    name: "updateTeam",
    resource: "teams",
    method: "PATCH",
    path: "/teams/{id}",
    summary: "Update an existing team",
    bodyContentType: "application/json",
    bodyFields: [
      ["name", "string", false],
      ["user_ids", "array", false],
    ],
    mutates: true,
  },
  {
    name: "listTicketForms",
    resource: "ticket-forms",
    method: "GET",
    path: "/ticket-forms",
    summary: "Get a list of ticket forms",
    mutates: false,
  },
  {
    name: "getTicketForm",
    resource: "ticket-forms",
    method: "GET",
    path: "/ticket-forms/{id}",
    summary: "Get a ticket form",
    mutates: false,
  },
  {
    name: "listTrainingData",
    resource: "training-data",
    method: "GET",
    path: "/training-data",
    summary: "List all training data configurations",
    mutates: false,
  },
  {
    name: "createTrainingData",
    resource: "training-data",
    method: "POST",
    path: "/training-data",
    summary: "Create a training data configuration",
    bodyContentType: "application/json",
    bodyFields: [
      ["training_data_name", "string", false],
      ["visibility", "string", false],
    ],
    mutates: true,
  },
  {
    name: "getTrainingData",
    resource: "training-data",
    method: "GET",
    path: "/training-data/{id}",
    summary: "Get a training data configuration by its ID",
    mutates: false,
  },
  {
    name: "deleteTrainingDataDocuments",
    resource: "training-data",
    method: "DELETE",
    path: "/training-data/{id}/documents",
    summary: "Delete training data documents",
    queryFields: [
      ["document_ids", "array", false],
      ["external_ids", "array", false],
    ],
    mutates: true,
  },
  {
    name: "uploadTrainingDataFiles",
    resource: "training-data",
    method: "POST",
    path: "/training-data/upload",
    summary: "Upload files as training data",
    bodyContentType: "multipart/form-data",
    bodyFields: [
      ["external_ids", "array", false],
      ["file_names", "array", false],
      ["files", "array", true],
      ["training_data_id", "string", false],
      ["training_data_name", "string", false],
      ["visibility", "string", false],
    ],
    mutates: true,
  },
  {
    name: "uploadTrainingDataFileContent",
    resource: "training-data",
    method: "POST",
    path: "/training-data/upload-content",
    summary: "Upload text content as training data",
    bodyContentType: "application/json",
    bodyFields: [
      ["content", "string", false],
      ["external_id", "string", false],
      ["file_name", "string", false],
      ["training_data_id", "string", false],
      ["training_data_name", "string", false],
      ["visibility", "string", false],
    ],
    mutates: true,
  },
  {
    name: "listUserRoles",
    resource: "user-roles",
    method: "GET",
    path: "/user-roles",
    summary: "Get a list of all user roles",
    mutates: false,
  },
  {
    name: "updateUser",
    resource: "user",
    method: "PATCH",
    path: "/users/{id}",
    summary: "Update a user",
    bodyContentType: "application/json",
    bodyFields: [
      ["avatar_url", "string", false],
      ["name", "string", false],
      ["role_id", "string", false],
      ["status", "string", false],
    ],
    mutates: true,
  },
] as const satisfies readonly EndpointDefinition[];

export const ENDPOINT_TOOL_NAMES = [
  "createAccount",
  "updateAccounts",
  "createAccountHighlight",
  "updateAccountHighlight",
  "deleteAccountHighlight",
  "updateAccount",
  "deleteAccount",
  "createAccountActivity",
  "uploadAccountFile",
  "listActivityTypes",
  "createAttachment",
  "listAuditLogs",
  "searchAuditLogs",
  "getCallRecording",
  "updateCallRecording",
  "searchCallRecordings",
  "createContact",
  "updateContact",
  "deleteContact",
  "listCustomFields",
  "createCustomField",
  "getCustomField",
  "updateCustomField",
  "listCustomObjects",
  "createCustomObject",
  "updateCustomObjects",
  "getCustomObject",
  "updateCustomObject",
  "deleteCustomObject",
  "searchCustomObjects",
  "getFeatureRequest",
  "updateFeatureRequest",
  "deleteFeatureRequest",
  "searchFeatureRequests",
  "importContact",
  "importIssue",
  "importIssueMessages",
  "listIssueStatuses",
  "createIssue",
  "updateIssue",
  "deleteIssue",
  "createIssueAiResponse",
  "linkExternalIssue",
  "updateIssueFollowers",
  "listIssueMessages",
  "deleteIssueMessage",
  "redactIssueMessage",
  "createIssueNote",
  "createIssueReply",
  "snoozeIssue",
  "listIssueThreads",
  "createIssueThread",
  "listIssueVoiceCalls",
  "listKnowledgeBases",
  "getKnowledgeBase",
  "listKnowledgeBaseArticles",
  "createKnowledgeBaseArticle",
  "getKnowledgeBaseArticle",
  "updateKnowledgeBaseArticle",
  "deleteKnowledgeBaseArticle",
  "requestKnowledgeBaseArticleReview",
  "listKnowledgeBaseCollections",
  "createKnowledgeBaseCollection",
  "getKnowledgeBaseCollection",
  "updateKnowledgeBaseCollection",
  "deleteKnowledgeBaseCollection",
  "createKnowledgeBaseRouteRedirect",
  "listMacroGroups",
  "listMacros",
  "createMacro",
  "getMacro",
  "updateMacro",
  "createMilestone",
  "getMilestone",
  "updateMilestone",
  "deleteMilestone",
  "createProject",
  "getProject",
  "updateProject",
  "deleteProject",
  "searchProjects",
  "listSurveys",
  "getSurvey",
  "listSurveyResponses",
  "searchSurveys",
  "listTags",
  "createTag",
  "getTag",
  "updateTag",
  "deleteTag",
  "listTasks",
  "createTask",
  "getTask",
  "updateTask",
  "deleteTask",
  "listTaskComments",
  "createTaskComment",
  "updateTaskComment",
  "deleteTaskComment",
  "searchTasks",
  "createTeam",
  "updateTeam",
  "listTicketForms",
  "getTicketForm",
  "listTrainingData",
  "createTrainingData",
  "getTrainingData",
  "deleteTrainingDataDocuments",
  "uploadTrainingDataFiles",
  "uploadTrainingDataFileContent",
  "listUserRoles",
  "updateUser",
] as const;
export const WRITE_ENDPOINT_TOOL_NAMES = [
  "createAccount",
  "updateAccounts",
  "createAccountHighlight",
  "updateAccountHighlight",
  "deleteAccountHighlight",
  "updateAccount",
  "deleteAccount",
  "createAccountActivity",
  "uploadAccountFile",
  "createAttachment",
  "updateCallRecording",
  "createContact",
  "updateContact",
  "deleteContact",
  "createCustomField",
  "updateCustomField",
  "createCustomObject",
  "updateCustomObjects",
  "updateCustomObject",
  "deleteCustomObject",
  "updateFeatureRequest",
  "deleteFeatureRequest",
  "importContact",
  "importIssue",
  "importIssueMessages",
  "createIssue",
  "updateIssue",
  "deleteIssue",
  "createIssueAiResponse",
  "linkExternalIssue",
  "updateIssueFollowers",
  "deleteIssueMessage",
  "redactIssueMessage",
  "createIssueNote",
  "createIssueReply",
  "snoozeIssue",
  "createIssueThread",
  "createKnowledgeBaseArticle",
  "updateKnowledgeBaseArticle",
  "deleteKnowledgeBaseArticle",
  "requestKnowledgeBaseArticleReview",
  "createKnowledgeBaseCollection",
  "updateKnowledgeBaseCollection",
  "deleteKnowledgeBaseCollection",
  "createKnowledgeBaseRouteRedirect",
  "createMacro",
  "updateMacro",
  "createMilestone",
  "updateMilestone",
  "deleteMilestone",
  "createProject",
  "updateProject",
  "deleteProject",
  "createTag",
  "updateTag",
  "deleteTag",
  "createTask",
  "updateTask",
  "deleteTask",
  "createTaskComment",
  "updateTaskComment",
  "deleteTaskComment",
  "createTeam",
  "updateTeam",
  "createTrainingData",
  "deleteTrainingDataDocuments",
  "uploadTrainingDataFiles",
  "uploadTrainingDataFileContent",
  "updateUser",
] as const;

export type EndpointToolName = (typeof ENDPOINT_TOOL_NAMES)[number];
export type WriteEndpointToolName = (typeof WRITE_ENDPOINT_TOOL_NAMES)[number];
